name: Update server blocklist
on:
  push:
    branches:
      - main
    paths:
      - 'blocklist.txt'
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Mastodont
        run: npm i -g mastodont

      - name: Update blocklist
        env:
          MASTODONT_ACCESS_TOKEN: ${{ secrets.MASTODONT_ACCESS_TOKEN }}
        run: |
          mastodont \
            -e https://masto.yttrx.com/admin/domain_blocks \
            -t $MASTODONT_ACCESS_TOKEN \
            -b https://raw.githubusercontent.com/waffle2k/mastodont/main/blocklist.txt \
            -s suspend \
            --private-comment "Added from shared blocklist, $(date %I)" \
            --non-interactive
